test for align watermark flow with port configuration
dbarashinvd/sonic-mgmt pull request #1
Opened 2022-11-16 11:38 UTC by dbarashinvd

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?
add a verification test for feature align watermark flow with port configuration

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-11-17 13:52 UTC, roysr-nv requested changes
Hi Doron, 

1. To cover the different scenarios, I suggest using pytest parametrization. It has some advantages comparing to the existing implementation.
2. There's no usage of allure step, it would be much more readable to have allure step when running the test with allure reporter.
3. Did you consider adding tests to cover the functional correctness of the counters?

2022-11-17 15:27 UTC, roysr-nv commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    skip_release(duthost, ["202111", "202106", "202012", "201911", "201811", "201803"])
you're missing 202205

2022-11-24 17:54 UTC, dbarashinvd commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    skip_release(duthost, ["202111", "202106", "202012", "201911", "201811", "201803"])
fixed

2022-11-24 17:56 UTC, dbarashinvd commented
> Hi Doron,
> 
> 1. To cover the different scenarios, I suggest using pytest parametrization. It has some advantages comparing to the existing implementation.
> 2. There's no usage of allure step, it would be much more readable to have allure step when running the test with allure reporter.
> 3. Did you consider adding tests to cover the functional correctness of the counters?

since we agreed to use randomization, didn't use pytest parametrization
added alure steps
random choice of reload/reboot and queue/watermark/pg-drop minimized the test duration to ~ 500 seconds.

2022-11-28 06:07 UTC, JibinBao commented
It seems there is missing a test: "Adding a port when watermark is enabled"  which is defined in HLD.
Can we need to add it?

2022-11-28 09:38 UTC, dbarashinvd commented
> It seems there is missing a test: "Adding a port when watermark is enabled" which is defined in HLD. Can we need to add it?

Hi Jibin,
this is a test defined in the feature implementation HLD, not the test plan HLD.
it's covered in a unit test and is part of the public PR for the implementation:
https://github.com/sonic-net/sonic-swss/pull/2525

Also note that it's not just adding a port now since there was an improvement adding counterpoll flex counters only for ports with queue or pg buffers:
https://github.com/sonic-net/sonic-swss/pull/2473/files
so now it's creating a buffer queue and buffer pg for a certain port and checks the flex counters created for it

if needed I can add such a test also for this test here but keep in mind it'll make the test longer than it's now, about 500 seconds after randomization requested by Roy.

2022-11-28 09:52 UTC, JibinBao commented
> > It seems there is missing a test: "Adding a port when watermark is enabled" which is defined in HLD. Can we need to add it?
> 
> Hi Jibin, this is a test defined in the feature implementation HLD, not the test plan HLD. it's covered in a unit test and is part of the public PR for the implementation: [sonic-net/sonic-swss#2525](https://github.com/sonic-net/sonic-swss/pull/2525)
> 
> Also note that it's not just adding a port now since there was an improvement adding counterpoll flex counters only for ports with queue or pg buffers: https://github.com/sonic-net/sonic-swss/pull/2473/files so now it's creating a buffer queue and buffer pg for a certain port and checks the flex counters created for it
> 
> if needed I can add such a test also for this test here but keep in mind it'll make the test longer than it's now, about 500 seconds after randomization requested by Roy.

Hi dbarashinvd,
I am not sure if the unit test can cover this scenario or not. If yes, I think it is ok. Otherwise, we will lose coverage.

2022-11-28 10:32 UTC, JibinBao commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    #logging.info("Verifying {} in output of {} on {} {}..."
Please remove unused code

2022-11-28 10:32 UTC, JibinBao commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    4. repeat this test 3 times, each time with different type [watermark,queue,pg-drop]
Since use randomization for the type [watermark,queue,pg-drop], please change the comments accordinlgy

2022-11-28 10:32 UTC, JibinBao commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    for counterpoll_parsed_dict in counterpoll_output:
These codes for parsing counterpoll show output are the same to that in verify_counterpoll_status. Can we define one function for them to void the redundant code?

2022-11-28 11:06 UTC, dbarashinvd commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    #logging.info("Verifying {} in output of {} on {} {}..."
done

2022-11-28 11:38 UTC, dbarashinvd commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    for counterpoll_parsed_dict in counterpoll_output:
done

2022-11-28 11:38 UTC, dbarashinvd commented on tests/platform_tests/counterpoll/test_counterpoll_watermark.py
> +    4. repeat this test 3 times, each time with different type [watermark,queue,pg-drop]
done

2022-11-28 15:48 UTC, roysr-nv approved these changes

2022-11-28 15:49 UTC, closed without merging